workflows:
  ios-linguareader:
    name: iOS LinguaReader
    environment:
      vars:
        PONS_API_KEY: $PONS_API_KEY

    scripts:
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/LinguaReader.xcworkspace \
                     -scheme LinguaReaderApp \
                     -sdk iphoneos \
                     -configuration Release clean build

artifacts:
  - build/ipa/*.ipa
